### ISSUE TITLE
Project 2 - Feedback

### ISSUE THREAD

**Issue by phlco** [juno0628/project#1]
Nice work!

Your routes look good. If you want to adhere to the principals of REST, you can structure your routes to work on a resource.  For instance, rather than `post('/newtopic')` we'd post data to the `topics` resource as `post('/topics')` and to get the representation of a new topic we'd use `get('/topics/new')`

When you write redirects, you're not rendering anything to ERB files, so you can skip using instance variables and just use local variables.

Be sure to be consistent with your white space around operators.

Your schema for the `users` table contains an `id` and a `user_id`. I think you're only using `id`. Is there a reason for the other?

Rather than writing your styles inline, 

```
  <span style="background-color: rgba(157,64,40,1);">comment</span>
```

Think about moving those styles over into classes in your CSS.

Your CSS looks good. Be sure to be consistent in your spacing. Use a space before curly braces.

```
.topic-page {
  //
}
```

Really great job adding chart.js!!

:+1:

**Comment by juno0628** [comment]
Thank you for your feedback. Route handlers for ERB files and instance variables have been fixed. CSS has been updated to change its theme.
